server:
  port: 7001
  error:
    include-message: always

logging:
  level:
    root: INFO
    microservices: DEBUG

---
#spring.profiles: docker
spring:
    config:
        activate:
            on-profile: docker
            
server:
  port: 8080
