server:
  port: 7003
  error.include-message: always

logging:
  level:
    root: INFO
    foo.bar: DEBUG

---
#spring.profiles: docker

#spring.profiles: docker
spring:
    config:
        activate:
            on-profile: docker
            
server:
  port: 8080
